apiVersion: v1
entries:
  llamacppgemma312b:
  - apiVersion: v2
    appVersion: unsloth/gemma-3-12b-it-GGUF
    created: "2026-03-20T21:22:57.132849-07:00"
    description: Gemma 3 12B IT Q8_0 served via llama.cpp — optimized for Olares One
    digest: ce2fa113cbd71c0d93f2b375f9afbe805913e32f75a9dc8d0adc2cdbda3c3f30
    name: llamacppgemma312b
    type: application
    urls:
    - https://trevenk.github.io/olares-models/charts/llamacppgemma312b-1.0.1.tgz
    version: 1.0.1
  - apiVersion: v2
    appVersion: unsloth/gemma-3-12b-it-GGUF
    created: "2026-03-20T21:22:57.1318429-07:00"
    description: Gemma 3 12B IT Q8_0 served via llama.cpp — optimized for Olares One
    digest: d40445569e0d996b6fb881bf41813fcb8b61533d4eb651e0f73da22d7375f597
    name: llamacppgemma312b
    type: application
    urls:
    - https://trevenk.github.io/olares-models/charts/llamacppgemma312b-1.0.0.tgz
    version: 1.0.0
  llamacppqwen35a3buncensored:
  - apiVersion: v2
    appVersion: HauhauCS/Qwen3.5-35B-A3B-Uncensored-HauhauCS-Aggressive
    created: "2026-03-20T21:22:57.1358881-07:00"
    description: Qwen3.5 35B-A3B Uncensored served via llama.cpp — optimized for Olares
      One
    digest: 66733b44e846c1a571d776fe77e7b01a80b48bb6168582f449f465819734c32f
    name: llamacppqwen35a3buncensored
    type: application
    urls:
    - https://trevenk.github.io/olares-models/charts/llamacppqwen35a3buncensored-1.0.14.tgz
    version: 1.0.14
  - apiVersion: v2
    appVersion: HauhauCS/Qwen3.5-35B-A3B-Uncensored-HauhauCS-Aggressive
    created: "2026-03-20T21:22:57.1343717-07:00"
    description: Qwen3.5 35B-A3B Uncensored served via llama.cpp — optimized for Olares
      One
    digest: 3e8da622bf075d175e83bcc4970af700aec8b7baafb845d9def3252f10f05b02
    name: llamacppqwen35a3buncensored
    type: application
    urls:
    - https://trevenk.github.io/olares-models/charts/llamacppqwen35a3buncensored-1.0.13.tgz
    version: 1.0.13
  - apiVersion: v2
    appVersion: HauhauCS/Qwen3.5-35B-A3B-Uncensored-HauhauCS-Aggressive
    created: "2026-03-20T21:22:57.1343717-07:00"
    description: Qwen3.5 35B-A3B Uncensored served via llama.cpp — optimized for Olares
      One
    digest: 76ceac142c1d9b5cc5ef63d11c5c0522871767d23fd08d7c52818cabc96d9a6a
    name: llamacppqwen35a3buncensored
    type: application
    urls:
    - https://trevenk.github.io/olares-models/charts/llamacppqwen35a3buncensored-1.0.12.tgz
    version: 1.0.12
  - apiVersion: v2
    appVersion: HauhauCS/Qwen3.5-35B-A3B-Uncensored-HauhauCS-Aggressive
    created: "2026-03-20T21:22:57.1343717-07:00"
    description: Qwen3.5 35B-A3B Uncensored served via llama.cpp — optimized for Olares
      One
    digest: c58a174350cb199f16508f2eefaaed39f67b88cfe8296d255e7f46ac53d2157c
    name: llamacppqwen35a3buncensored
    type: application
    urls:
    - https://trevenk.github.io/olares-models/charts/llamacppqwen35a3buncensored-1.0.11.tgz
    version: 1.0.11
  - apiVersion: v2
    appVersion: HauhauCS/Qwen3.5-35B-A3B-Uncensored-HauhauCS-Aggressive
    created: "2026-03-20T21:22:57.1343717-07:00"
    description: Qwen3.5 35B-A3B Uncensored served via llama.cpp — optimized for Olares
      One
    digest: 6c46a9e0a4dfa9d31d1ceb277f2660317f2c788f7267e00b04a05c9e29b167f2
    name: llamacppqwen35a3buncensored
    type: application
    urls:
    - https://trevenk.github.io/olares-models/charts/llamacppqwen35a3buncensored-1.0.10.tgz
    version: 1.0.10
  - apiVersion: v2
    appVersion: HauhauCS/Qwen3.5-35B-A3B-Uncensored-HauhauCS-Aggressive
    created: "2026-03-20T21:22:57.1384096-07:00"
    description: Qwen3.5 35B-A3B Uncensored served via llama.cpp — optimized for Olares
      One
    digest: 495dbf1983ca913ba34a3a1db13ac1b3f06e59e376e1a4a1cffa5e4849fd1b14
    name: llamacppqwen35a3buncensored
    type: application
    urls:
    - https://trevenk.github.io/olares-models/charts/llamacppqwen35a3buncensored-1.0.8.tgz
    version: 1.0.8
  - apiVersion: v2
    appVersion: HauhauCS/Qwen3.5-35B-A3B-Uncensored-HauhauCS-Aggressive
    created: "2026-03-20T21:22:57.1384096-07:00"
    description: Qwen3.5 35B-A3B Uncensored served via llama.cpp — optimized for Olares
      One
    digest: 3dd428d49a9484c6dae23f825c887386bee03b30d637b096d0d320c8267f80e8
    name: llamacppqwen35a3buncensored
    type: application
    urls:
    - https://trevenk.github.io/olares-models/charts/llamacppqwen35a3buncensored-1.0.7.tgz
    version: 1.0.7
  - apiVersion: v2
    appVersion: HauhauCS/Qwen3.5-35B-A3B-Uncensored-HauhauCS-Aggressive
    created: "2026-03-20T21:22:57.1374092-07:00"
    description: Qwen3.5 35B-A3B Uncensored served via llama.cpp — optimized for Olares
      One
    digest: ba4a96dcd620d822e3bf1650b8ac5e03ce8968b6980955a73939bef21f955c04
    name: llamacppqwen35a3buncensored
    type: application
    urls:
    - https://trevenk.github.io/olares-models/charts/llamacppqwen35a3buncensored-1.0.6.tgz
    version: 1.0.6
  - apiVersion: v2
    appVersion: HauhauCS/Qwen3.5-35B-A3B-Uncensored-HauhauCS-Aggressive
    created: "2026-03-20T21:22:57.1374092-07:00"
    description: Qwen3.5 35B-A3B Uncensored served via llama.cpp — optimized for Olares
      One
    digest: 297dd38e83b0422328323048748efc48e16361b664e5184a61b2dfd5e50f0933
    name: llamacppqwen35a3buncensored
    type: application
    urls:
    - https://trevenk.github.io/olares-models/charts/llamacppqwen35a3buncensored-1.0.5.tgz
    version: 1.0.5
  - apiVersion: v2
    appVersion: HauhauCS/Qwen3.5-35B-A3B-Uncensored-HauhauCS-Aggressive
    created: "2026-03-20T21:22:57.1374092-07:00"
    description: Qwen3.5 35B-A3B Uncensored served via llama.cpp — optimized for Olares
      One
    digest: 4006ad7d72520ccd0ad9c5f8d36c492829dcc8362c96428076ac8f589957103c
    name: llamacppqwen35a3buncensored
    type: application
    urls:
    - https://trevenk.github.io/olares-models/charts/llamacppqwen35a3buncensored-1.0.4.tgz
    version: 1.0.4
  - apiVersion: v2
    appVersion: HauhauCS/Qwen3.5-35B-A3B-Uncensored-HauhauCS-Aggressive
    created: "2026-03-20T21:22:57.1358881-07:00"
    description: Qwen3.5 35B-A3B Uncensored served via llama.cpp — optimized for Olares
      One
    digest: 2a9623584b5604caeeb7897add7f743b69a866fc7d424634eaac9a9ed236d4d6
    name: llamacppqwen35a3buncensored
    type: application
    urls:
    - https://trevenk.github.io/olares-models/charts/llamacppqwen35a3buncensored-1.0.3.tgz
    version: 1.0.3
  - apiVersion: v2
    appVersion: HauhauCS/Qwen3.5-35B-A3B-Uncensored-HauhauCS-Aggressive
    created: "2026-03-20T21:22:57.1358881-07:00"
    description: Qwen3.5 35B-A3B Uncensored served via llama.cpp — optimized for Olares
      One
    digest: 6b7ff517dbb2a7bb2394a0831921586e6d946ea0b35f5e3822527ae1df77599b
    name: llamacppqwen35a3buncensored
    type: application
    urls:
    - https://trevenk.github.io/olares-models/charts/llamacppqwen35a3buncensored-1.0.2.tgz
    version: 1.0.2
  - apiVersion: v2
    appVersion: HauhauCS/Qwen3.5-35B-A3B-Uncensored-HauhauCS-Aggressive
    created: "2026-03-20T21:22:57.132849-07:00"
    description: Qwen3.5 35B-A3B Uncensored served via llama.cpp — optimized for Olares
      One
    digest: 454a0895a2167bef90f57d28b98f24c7f11e969db681ba7ebcb23b53b59995c0
    name: llamacppqwen35a3buncensored
    type: application
    urls:
    - https://trevenk.github.io/olares-models/charts/llamacppqwen35a3buncensored-1.0.1.tgz
    version: 1.0.1
  - apiVersion: v2
    appVersion: HauhauCS/Qwen3.5-35B-A3B-Uncensored-HauhauCS-Aggressive
    created: "2026-03-20T21:22:57.132849-07:00"
    description: Qwen3.5 35B-A3B Uncensored served via llama.cpp — optimized for Olares
      One
    digest: f5d638bc67a76b791ccd17e5728f6b2d804f4a0d74569a3b77308acde4156714
    name: llamacppqwen35a3buncensored
    type: application
    urls:
    - https://trevenk.github.io/olares-models/charts/llamacppqwen35a3buncensored-1.0.0.tgz
    version: 1.0.0
  llamacppqwen314b:
  - apiVersion: v2
    appVersion: lm-kit/qwen-3-14b-instruct-gguf
    created: "2026-03-20T21:22:57.132849-07:00"
    description: Qwen3 14B Instruct Q6_K served via llama.cpp — optimized for Olares
      One
    digest: 3036b9d258a2aa2b47c78f1016f081eeb367a454aae535c3064cac23444e8acc
    name: llamacppqwen314b
    type: application
    urls:
    - https://trevenk.github.io/olares-models/charts/llamacppqwen314b-1.0.1.tgz
    version: 1.0.1
  - apiVersion: v2
    appVersion: lm-kit/qwen-3-14b-instruct-gguf
    created: "2026-03-20T21:22:57.132849-07:00"
    description: Qwen3 14B Instruct Q6_K served via llama.cpp — optimized for Olares
      One
    digest: 22adf868cfac936564366e51f012e44818a5b1f72f804ee48adb49d9203cc81f
    name: llamacppqwen314b
    type: application
    urls:
    - https://trevenk.github.io/olares-models/charts/llamacppqwen314b-1.0.0.tgz
    version: 1.0.0
  llamacppqwen3coder30ba3b:
  - apiVersion: v2
    appVersion: Qwen/Qwen3-Coder-30B-A3B-Instruct
    created: "2026-03-20T21:22:57.1441047-07:00"
    description: Qwen3 Coder 30B-A3B Instruct served via llama.cpp — optimized for
      Olares One
    digest: 416be882c01b2b0d03665e6de80247205959193df38bb7ddd1a2497c8a5cbf50
    name: llamacppqwen3coder30ba3b
    type: application
    urls:
    - https://trevenk.github.io/olares-models/charts/llamacppqwen3coder30ba3b-1.0.9.tgz
    version: 1.0.9
  - apiVersion: v2
    appVersion: Qwen/Qwen3-Coder-30B-A3B-Instruct
    created: "2026-03-20T21:22:57.1435551-07:00"
    description: Qwen3 Coder 30B-A3B Instruct served via llama.cpp — optimized for
      Olares One
    digest: 0646ebcf31ba2e8a4f21dda6afaa400a02431cbf2e0c4321bdd6af6d0ce4f336
    name: llamacppqwen3coder30ba3b
    type: application
    urls:
    - https://trevenk.github.io/olares-models/charts/llamacppqwen3coder30ba3b-1.0.8.tgz
    version: 1.0.8
  - apiVersion: v2
    appVersion: Qwen/Qwen3-Coder-30B-A3B-Instruct
    created: "2026-03-20T21:22:57.1435551-07:00"
    description: Qwen3 Coder 30B-A3B Instruct served via llama.cpp — optimized for
      Olares One
    digest: cad7d7ac5ad85ba4219e9aed1a99d7f0634ace63f8d063f993fcb020f3a5129c
    name: llamacppqwen3coder30ba3b
    type: application
    urls:
    - https://trevenk.github.io/olares-models/charts/llamacppqwen3coder30ba3b-1.0.7.tgz
    version: 1.0.7
  - apiVersion: v2
    appVersion: Qwen/Qwen3-Coder-30B-A3B-Instruct
    created: "2026-03-20T21:22:57.1430427-07:00"
    description: Qwen3 Coder 30B-A3B Instruct served via llama.cpp — optimized for
      Olares One
    digest: 25304216cc2406259576d3a769828b1a789d311710897bb0e5a223a57b6c8498
    name: llamacppqwen3coder30ba3b
    type: application
    urls:
    - https://trevenk.github.io/olares-models/charts/llamacppqwen3coder30ba3b-1.0.6.tgz
    version: 1.0.6
  - apiVersion: v2
    appVersion: Qwen/Qwen3-Coder-30B-A3B-Instruct
    created: "2026-03-20T21:22:57.1425355-07:00"
    description: Qwen3 Coder 30B-A3B Instruct served via llama.cpp — optimized for
      Olares One
    digest: 467afcace57fdeef893292b13cb3b57e0ac134ea1c42de4624c672d81aa3c29a
    name: llamacppqwen3coder30ba3b
    type: application
    urls:
    - https://trevenk.github.io/olares-models/charts/llamacppqwen3coder30ba3b-1.0.5.tgz
    version: 1.0.5
  - apiVersion: v2
    appVersion: Qwen/Qwen3-Coder-30B-A3B-Instruct
    created: "2026-03-20T21:22:57.1420213-07:00"
    description: Qwen3 Coder 30B-A3B Instruct served via llama.cpp — optimized for
      Olares One
    digest: 8edf0ffe7c907020a3165c48d4faacda05eb7d3b42f91835364af69c3109bc6f
    name: llamacppqwen3coder30ba3b
    type: application
    urls:
    - https://trevenk.github.io/olares-models/charts/llamacppqwen3coder30ba3b-1.0.3.tgz
    version: 1.0.3
  - apiVersion: v2
    appVersion: Qwen/Qwen3-Coder-30B-A3B-Instruct
    created: "2026-03-20T21:22:57.1420213-07:00"
    description: Qwen3 Coder 30B-A3B Instruct served via llama.cpp — optimized for
      Olares One
    digest: f854d41c96070566aa9f0abd6a710f711456adeed7ed225beb7390549956ac7e
    name: llamacppqwen3coder30ba3b
    type: application
    urls:
    - https://trevenk.github.io/olares-models/charts/llamacppqwen3coder30ba3b-1.0.2.tgz
    version: 1.0.2
  - apiVersion: v2
    appVersion: Qwen/Qwen3-Coder-30B-A3B-Instruct
    created: "2026-03-20T21:22:57.1415109-07:00"
    description: Qwen3 Coder 30B-A3B Instruct served via llama.cpp — optimized for
      Olares One
    digest: c5f3c88551daed754d123cd80e46a0ec6f04d52e7017d017c3cbb07895309391
    name: llamacppqwen3coder30ba3b
    type: application
    urls:
    - https://trevenk.github.io/olares-models/charts/llamacppqwen3coder30ba3b-1.0.1.tgz
    version: 1.0.1
  - apiVersion: v2
    appVersion: Qwen/Qwen3-Coder-30B-A3B-Instruct
    created: "2026-03-20T21:22:57.1415109-07:00"
    description: Qwen3 Coder 30B-A3B Instruct served via llama.cpp — optimized for
      Olares One
    digest: f955f9ba0993a864394f5b0265ed6f7997fa6d4ae67a430bed2f5afe3db82a1d
    name: llamacppqwen3coder30ba3b
    type: application
    urls:
    - https://trevenk.github.io/olares-models/charts/llamacppqwen3coder30ba3b-1.0.0.tgz
    version: 1.0.0
  vllmqwen3coder30ba3bfp4:
  - apiVersion: v2
    appVersion: NVFP4/Qwen3-Coder-30B-A3B-Instruct-FP4
    created: "2026-03-20T21:22:57.1446194-07:00"
    description: Qwen3 Coder 30B-A3B FP4 served via vLLM — optimized for Olares One
    digest: 41fce62b0aa8fe4c048c66a8b86d5d08ff2867f5e29539ee6e71a881389b8b75
    name: vllmqwen3coder30ba3bfp4
    type: application
    urls:
    - https://trevenk.github.io/olares-models/charts/vllmqwen3coder30ba3bfp4-1.0.3.tgz
    version: 1.0.3
  - apiVersion: v2
    appVersion: NVFP4/Qwen3-Coder-30B-A3B-Instruct-FP4
    created: "2026-03-20T21:22:57.1446194-07:00"
    description: Qwen3 Coder 30B-A3B FP4 served via vLLM — optimized for Olares One
    digest: 46dfff0c57e9fa40ccd75ea71c377cdea55758591aabad802e53ff49af5a6df4
    name: vllmqwen3coder30ba3bfp4
    type: application
    urls:
    - https://trevenk.github.io/olares-models/charts/vllmqwen3coder30ba3bfp4-1.0.2.tgz
    version: 1.0.2
  - apiVersion: v2
    appVersion: NVFP4/Qwen3-Coder-30B-A3B-Instruct-FP4
    created: "2026-03-20T21:22:57.1446194-07:00"
    description: Qwen3 Coder 30B-A3B FP4 served via vLLM — optimized for Olares One
    digest: cbb5756469d56d60eb0b0ff7dde02c752aac8d37c14a3f03b38cd4734a1da086
    name: vllmqwen3coder30ba3bfp4
    type: application
    urls:
    - https://trevenk.github.io/olares-models/charts/vllmqwen3coder30ba3bfp4-1.0.1.tgz
    version: 1.0.1
  - apiVersion: v2
    appVersion: NVFP4/Qwen3-Coder-30B-A3B-Instruct-FP4
    created: "2026-03-20T21:22:57.1446194-07:00"
    description: Qwen3 Coder 30B-A3B FP4 served via vLLM — optimized for Olares One
    digest: 375645e98c7755df431dcc34a6795f03121eeed84e7c1fd7dd01cabbac58a825
    name: vllmqwen3coder30ba3bfp4
    type: application
    urls:
    - https://trevenk.github.io/olares-models/charts/vllmqwen3coder30ba3bfp4-1.0.0.tgz
    version: 1.0.0
generated: "2026-03-20T21:22:57.1318429-07:00"
