admin: ""
bfl:
  username: ""
userspace:
  appData: ""
  appCache: ""
  userData: ""

image:
  repository: codercom/code-server
  tag: latest
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: '4'
    memory: 4Gi
